if: tag IS blank
git:
  depth: 1
sudo: false
language: node_js
node_js:
  - "8"
env:
  - CXX=g++-4.8

before_install:
  - npm install -g lerna yarn
  - ./scripts/checkout-opticss.sh build/opticss
  - ./scripts/link-to-opticss.js --file build/opticss

install:
  - lerna bootstrap --registry=https://registry.npmjs.org/
  - ./scripts/link-to-opticss.js --version build/opticss
  - ./scripts/link-to-opticss.js --symlink build/opticss

script: lerna run test
